### ISSUE TITLE
Persisting replica connections

### ISSUE THREAD

**Issue by pedrocunha** [WeTransfer/activerecord_autoreplica#2]
Hi,

Thanks for putting out this gem, as it's extremely simple and perfect for a use case where you only need a slave read scenario.

I've a question: is there a hard requirement / limitation for not persisting connections to the replica? [here](https://github.com/WeTransfer/activerecord_autoreplica/blob/master/lib/activerecord_autoreplica.rb#L58)

Thanks

**Comment by julik** [comment]
There isn't. It is done this way because the method call to the `using_read_replica_at` gets a connection specification, so the connection details might change on every call. I will have a look whether there can be a simple way to override this. Are you in a situation with many replica use blocks per page, so that the reconnect overhead becomes too big?

**Comment by julik** [comment]
We could add something like `using_replica_connection_pool(pool)` but that would assume that you already have access to the connection pool object, and this is not extremely novice-friendly. OTOH if you need read replicas you are past the novice point I guess, so would that work for you?

**Comment by pedrocunha** [comment]
> Are you in a situation with many replica use blocks per page, so that the reconnect overhead becomes too big?

No, we only connect once per controller action call.

Correct me if I'm wrong but the current implementation might add extra connection http/ruby time when establishing and handling SSL connections every time the block is executed. 


Also assuming the fact probably everyone is using either Unicorn or Puma or alike in production we need to handle properly the forking / sigterm if we were to persist connections.

I think in order to solve the above we might need to be able to add the API the ability to initialize a pool and give that to a block to use it, but also as important give methods to reconnect the pool on forking / disconnect on sigterm. 

Does that make sense? If so, would that be interesting functionality to add to this? I'm really trying to avoid Octopus to our codebase as it's a massive boilerplate for just read slave functionality.

**Comment by julik** [comment]
Yes, it could add some overhead for connection management of course. For us it works better this way though because managing persistent AR connections with threading/forking already is somewhat of a pain. 

That said though, I think being able to handle replica connections from a pool is a reasonable feature to have. Would you be interested to try a hand at an implementation? You could solve this by adding an extra argument to suppress the pool disconnect, and a top-level module method named something like `with_read_replica_from_pool(pool)`.

**Comment by pedrocunha** [comment]
I'll try to have it go and see how it turns out. Thanks for your replies.

**Comment by julik** [comment]
Closing this unless there are other suggestions on how to implement this feature
